### ISSUE TITLE
package-lock.json causing npm install to fail with: fatal: reference is not a tree: cb05d9d441a2e7a5c7a6db0ff132c7e671f4cfe5

### ISSUE THREAD

**Issue by ejlofgren** [eddyerburgh/jest-vue-starter#1]
Thanks for writing the article and creating this sample project! As of now, npm install fails:

```
git clone https://github.com/eddyerburgh/vue-unit-test-starter.git
Cloning into 'vue-unit-test-starter'...
remote: Enumerating objects: 42, done.
remote: Total 42 (delta 0), reused 0 (delta 0), pack-reused 42
Unpacking objects: 100% (42/42), done.

cd vue-unit-test-starter
npm install
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout cb05d9d441a2e7a5c7a6db0ff132c7e671f4cfe5
npm ERR! fatal: reference is not a tree: cb05d9d441a2e7a5c7a6db0ff132c7e671f4cfe5
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elijah Lofgren\AppData\Roaming\npm-cache\_logs\2018-09-28T15_27_11_867Z-debug.log

```

A fix is to delete package-lock.json and then run npm install and then run npm install --save-dev tape vue-test-utils@1.0.0-beta as per https://medium.freecodecamp.org/how-to-write-blazing-fast-vue-unit-tests-with-tape-and-vue-test-utils-be069ccd4acf

The line causing the issue in package-lock.json is:
```

 "vue-test-utils": {
      "version": "git+https://github.com/vuejs/vue-test-utils.git#cb05d9d441a2e7a5c7a6db0ff132c7e671f4cfe5",
      "dev": true
    },
```

The fixed line looks like this:

```
    "vue-test-utils": {
      "version": "1.0.0-beta",
      "resolved": "https://registry.npmjs.org/vue-test-utils/-/vue-test-utils-1.0.0-beta.tgz",
      "integrity": "sha512-XL9eSD8q9NMyjk+uwxCrse3lOWfIbcLgJILzLHCu01KrVfReLIovqa7DTn0CTXLRe98EHrxBYbAexW4DT3MPDg==",
      "dev": true,
      "requires": {
        "lodash": "4.17.11"
      }
    },
```

I would consider submitting a PR but didn't want to assume you'd like versions like lodash etc incremented to their latest minor releases.

**Comment by eddyerburgh** [comment]
Thanks @ejlofgren , I've updated the package-lock and removed vue-test-utils from the dependencies. I've also updated the article to use the recent @vue/test-utils package, rather than the vue-test-utils package
